export const GET_FILMS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_FILMS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_FILMS_ERROR = 'GET_POSTS_ERROR';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const SET_FAVORITE = 'SET_FAVORITE';